### ISSUE TITLE
setCounter doesn't create a new counter

### ISSUE THREAD

**Issue by camilosw** [osv/meteor-mongo-counter#2]
I need to create a new counter with an initial value. I expected that setCounter could do that, but I ended doing something that doesn't appear to be intuitive:

``` javascript
incrementCounter('counterCollection', 'myCounter');
setCounter('counterCollection', 'myCounter', 10); 
```

**Comment by osv** [comment]
Hello, are you sure you install `osv:mongo-counter` package? Check `.meteor/versions`

I just clone and rerun tests `meteor test-packages ./` and it looks ok.

**Comment by osv** [comment]
Oh, I confirm bug, it happen when you setCounter on **new** counter name, need upsert.

fixed https://github.com/osv/meteor-mongo-counter/commit/fc6c65382cd670d41501e4f98abcce9dc65b7809,

update your version to `osv:mongo-counter@0.2.0`
