### ISSUE TITLE
Migration from mrt:meteor-counter

### ISSUE THREAD

**Issue by jimmiebtlr** [osv/meteor-mongo-counter#3]
I'm attempting to use you're package instead of mrt:mongo-counter.  I've upgraded, and added osv:mongo-counter.

And changed instance's of 

```
incrementCounter("vendorCount");
```

to

```
incrementCounter('awwx_mongo_counter',"vendorCount");
```

The values in the updated application don't continue, where mrt:mongo-counter left off though.  Any suggestions?

**Comment by osv** [comment]
Sorry for incorrect documentation, this is fork of https://github.com/Konecty/meteor-mongo-counter and MongoDB's counter key has been changed in Kinecty fork (https://github.com/Konecty/meteor-mongo-counter/commit/0b6d0493a4da72359707d837593fb157ebd004b4). You should manually write migration, copy key value from collection `awwx_mongo_counter` "seq"  to "next_val".
