### ISSUE TITLE
incrementCounter returns 'undefined' after upgrade to Meteor 1.4

### ISSUE THREAD

**Issue by domiko** [osv/meteor-mongo-counter#5]
incrementCounter returns 'undefined' after upgrade to Meteor 1.4.

**Comment by domiko** [comment]
https://github.com/Konecty/meteor-mongo-counter/commit/cca56926365e634e4cac0894685bcf7832054efe

**Comment by osv** [comment]
Thank you for report! Sorry for long delay, I fix in 2 days.

**Comment by pdrummond** [comment]
I am also getting this error.  Any info on when this will be fixed?

**Comment by domiko** [comment]
Hey Paul.

I personally replicated the code (to JavaScript), fixed it (1 line) and put
it in directly in my project.

Regards,
Dominique.

2016-08-09 0:11 GMT+02:00 Paul Drummond notifications@github.com:

**Comment by osv** [comment]
Fixed. You can bump to `osv:mongo-counter@0.3.0`. Sorry for delay again. I close issue.
