### ISSUE TITLE
Meteor 1.4.1 and mongo counter 0.3.0: tinytest is not defined

### ISSUE THREAD

**Issue by kartojal** [osv/meteor-mongo-counter#6]
Today i updated to meteor 1.4.1 and osv:mongo-counter@0.3.0. When i want to run Meteor with osv@mongo-counter@0.3.0, this error happens:

user@host$ meteor

```

ReferenceError: Tinytest is not defined.

W20160822-09:13:45.295(2)? (STDERR) /home/$user/.meteor/packages/meteor-tool/.1.4.1.1bywalu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160822-09:13:45.295(2)? (STDERR)                             throw(ex);
W20160822-09:13:45.295(2)? (STDERR)                             ^
W20160822-09:13:45.296(2)? (STDERR)           
W20160822-09:13:45.296(2)? (STDERR) ReferenceError: Tinytest is not defined
W20160822-09:13:45.297(2)? (STDERR)     at packages/osv_mongo-counter/counter-tests.coffee.js:2:1
W20160822-09:13:45.297(2)? (STDERR)     at packages/osv_mongo-counter/counter-tests.coffee.js:32:1
W20160822-09:13:45.297(2)? (STDERR)     at packages/osv_mongo-counter/counter-tests.coffee.js:32:1
W20160822-09:13:45.298(2)? (STDERR)     at /home/$user/testimonium/repos/testimonium/.meteor/local/build/programs/server/boot.js:292:10
W20160822-09:13:45.299(2)? (STDERR)     at Array.forEach (native)
W20160822-09:13:45.299(2)? (STDERR)     at Function._.each._.forEach (/home/$user/.meteor/packages/meteor-tool/.1.4.1.1bywalu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160822-09:13:45.299(2)? (STDERR)     at /home/$user/testimonium/repos/testimonium/.meteor/local/build/programs/server/boot.js:128:5
=> Exited with code: 1                        
=> Your application is crashing. Waiting for file change.
```

I tried to install the tinytest package and it doesn't fix it. The actual fix is to downgrade osv:mongo-counter to 0.2.1 . Do you have any hint?

Thanks

**Comment by Siphion** [comment]
+1

**Comment by tarunbatra** [comment]
Pinning it to `0.2.1` prevents it from throwing error, but the package silently fails and returns `undefined`

**Comment by gaiazov** [comment]
I created a pull request #7 for a proper fix

**Comment by osv** [comment]
Hm, why counter-tests.coffee.js... it used only for test? Let me inspect for different versions

**Comment by osv** [comment]
What I found. When I clone this package some where and then link package:

```
ln -s ~/work/my/meteor-mongo-counter packages/osv:meteor-mongo-counter
```

all work without error, when I download from atmosphere I found next files in local meteor dir: 

```
.meteor/packages/osv_mongo-counter/.0.3.0.1v74i3a++os+web.browser+web.cordova/os/packages/osv_mongo-counter:
  total used in directory 16K available 196402044
  drwxr-xr-x 2 olexandr 4,0K 2016-08-25 11:41 ./
  drwxr-xr-x 3 olexandr 4,0K 2016-08-25 11:41 ../
  -r--r--r-- 1 olexandr 2,0K 2016-08-25 11:41 counter.coffee.js
  -r--r--r-- 1 olexandr 1,3K 2016-08-25 11:41 counter-tests.coffee.js
```

So prear #7 not solve problem because no one need this test file in production. It looks somehow code was published in wrong way to atmosphere. Will fix soon

(created issue: https://github.com/meteor/meteor/issues/7709)

**Comment by tarunbatra** [comment]
@osv You're right. Cloning the repo to the packages folder works fine but using the atmosphere version doesn't.
Do you have any updates?

**Comment by osv** [comment]
@tarunbatra I'm sorry for so long delay, I remove test file and comment out onTest bock then I publish... I test osv:mongo-counter@0.3.5 and looks it work now.

P.S. I really don't love how meteor designed and that many things that work before one day broke :(

**Comment by tarunbatra** [comment]
@osv updated to 0.3.5 and it works fine! Many thanx. Hope they fix it for long run.
