### ISSUE TITLE
incrementCounter is not defined

### ISSUE THREAD

**Issue by peeyushjss** [osv/meteor-mongo-counter#8]
Please explain "incrementCounter is not defined" why this is coming? I am using this as 

incrementCounter("__counters__", 'scheduleNumber');

It's working fine according to functionality but exception is coming "incrementCounter is not defined". Please help as soon as possible.

**Comment by osv** [comment]
I just create empty project and all work fine for me.

Use this lib only in **server** only. If you need expose lib to client than create `method` in server and use this lib in method.

*Feel free to open again issue if need*
